services:
  snowflake:
    image: jxch/snowflake  # 使用 jxch/snowflake 镜像
    ports:
      - "5000:8000"  # 将容器内的 5000 端口映射到主机
    environment:
      DATACENTER_ID: 1           # 数据中心 ID
      WORKER_ID: 1               # 工作节点 ID
      LOGICAL_CLOCK: "true"  # 是否启用逻辑时钟 (1=启用, 0=禁用)

